# Generated by Django 5.2.7 on 2025-10-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MSC-S', 'Msc Student'), ('PHD-S', 'Phd Student'), ('POST-DOC', 'Post-Doc'), ('PROF.', 'Prof.'), ('ASSO.PROF', 'Associate Prof.'), ('ASSI.PROF', 'Assistant Prof.'), ('OTHER', 'Other')], default='PHD-S', max_length=300)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(default='+216 00 000 000', max_length=20)),
                ('institution', models.CharField(max_length=500)),
                ('laboratory', models.CharField(max_length=500)),
                ('presentation', models.CharField(choices=[('ORAL', 'Oral presentation.'), ('POSTER', 'Poster presentation.')], default='POSTER', max_length=300)),
                ('subject', models.CharField(max_length=500)),
                ('topic', models.CharField(choices=[('TOPIC1', 'Renewable Energy & Sustainability.'), ('TOPIC2', 'Hydrogen Technology & Energy Storage.'), ('TOPIC3', 'Cross-cutting Challenges & Advanced Materials.'), ('TOPIC4', 'Modeling, Simulation & Digitalization.')], default='TOPIC1', max_length=500)),
                ('filename', models.CharField(max_length=300)),
                ('document', models.FileField(upload_to='documents/submissions/abstracts/')),
                ('demande_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
