# Generated by Django 5.2.7 on 2025-10-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractsubmission',
            name='filename',
        ),
    ]
