"""
Django settings for amgecsite project.

Generated by 'django-admin startproject' using Django 5.2.7.

Developed by Najla BEN HASSINE

SEP 25
"""


from pathlib import Path


### packages needed for .env
import sys
import os
from dotenv import load_dotenv
# Load environment variables from .env file
load_dotenv()


### packages needed for french
import locale
import datetime
locale.setlocale(locale.LC_TIME, 'fr_FR.UTF-8') 


#FontAwesome integration
sys.modules['fontawesome_free'] = __import__('fontawesome-free')


############################
##                        ##
## SERVER SETTING         ##
##                        ##
############################

#-- TO CHANGE IN PROD----
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG')
ALLOWED_HOSTS= list(os.getenv("ALLOWED_HOSTS"))

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
DEFAULT_FROM_EMAIL= os.getenv('DEFAULT_FROM_EMAIL')
NOTIFY_EMAIL= os.getenv('NOTIFY_EMAIL')

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS')


############################
##                        ##
## STATICS FILES SETTING  ##
##                        ##
############################

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent#.parent

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
)
STATIC_ROOT = BASE_DIR / 'staticfiles'




############################
##                        ##
## URLS SETTING           ##
##                        ##
############################
ROOT_URLCONF = "amgecws.urls"
WSGI_APPLICATION = "amgecws.wsgi.application"
LOGIN_REDIRECT_URL = 'home'


############################
##                        ##
## TEMPLATES SETTING      ##
##                        ##
############################
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        #Modified by bhn 030925
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


############################
##                        ##
## APPLICATIONS SETTING   ##
##                        ##
############################
INSTALLED_APPS = [
    "clearcache",
    "admin_interface",
    "colorfield",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_bootstrap5",
    "django_bootstrap_icons",
    "crispy_bootstrap5",
    "crispy_forms",
    "import_export",
    "django_filters",
    'skelton',
    'submissions',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


############################
##                        ##
## MIDDLEWARE   SETTING   ##
##                        ##
############################
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]


#######################
##                   ##
## DATABASE SETTING  ##
##                   ##
#######################

# SETUP MYSQL DB
DATABASES = {
    'default': {
          'ENGINE': 'django.db.backends.mysql',
          'NAME': os.getenv('DB_NAME'),
          'HOST': os.getenv('DB_HOST'),
          'PORT': os.getenv('DB_PORT'),
          'USER': os.getenv('DB_LOGIN'),
          'PASSWORD': os.getenv('DB_PASS'),
        },
    'OPTIONS': { 'init_command': 'SET storage_engine=INNODB;' }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]

####################################
##                                ##
## INTERNATIONALIZATION  SETTING  ##
##                                ##
###################################
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


#######################
##                   ##
## CACHE SETTING     ##
##                   ##
#######################
CLEAR_CACHE_ON_RESTART = True
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = True



#######################
##                   ##
## DEFAULT TEMPLATE  ##
##                   ##
#######################
#CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
#CRISPY_TEMPLATE_PACK = "bootstrap5"

#CRISPY_TEMPLATE_PACK = "unfold_crispy"
#CRISPY_ALLOWED_TEMPLATE_PACKS = ["unfold_crispy"]

#######################
##                   ##
## ADMIN INTERFACE  ##
##                   ##
#######################
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

#######################
##                   ##
## FILTER CONFIGUR  ##
##                   ##
#######################
ADMIN_FILTER_HISTORY_LIMIT = 3
ADMIN_FILTER_TRUNCATE_HISTORY = True
ADMIN_FILTER_URL_PATH = 'filter/'


