# Generated by Django 5.2.7 on 2025-10-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(default='+216 00 000 000', max_length=20)),
                ('demande', models.CharField(choices=[('INFO-VENUE', 'VENUE'), ('INFO-ABSTRACT', 'ABSTRACT SUBMISSION'), ('INFO-PAPER', 'PAPER SUBMISSION'), ('INFO-REGISTRATION', 'REGISTRATION'), ('OTHER-DEMANDE', 'OTHERS')], default='INFO-ABSTRACT', max_length=300)),
                ('message', models.TextField()),
                ('demande_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
